name: Test
on: [push]

jobs:
  test:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Do unit test
      run: go test -v .

